apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "webserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "webserver.name" . }}
    helm.sh/chart: {{ include "webserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi